# Generated by Django 5.2.13 on 2026-04-22 11:52

from django.conf import settings
from django.db import migrations, models


def remove_duplicate_applications(apps, schema_editor):
    Application = apps.get_model('backend', 'Application')
    seen = set()

    for application in Application.objects.order_by('job_id', 'applicant_id', 'id'):
        key = (application.job_id, application.applicant_id)
        if key in seen:
            application.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_applications_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_applications, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('job', 'applicant'), name='unique_application_per_job_applicant'),
        ),
    ]
